name: Deploy 2el-front

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            PROJECT_DIR=/var/www/2el-front

            # Подготовка папки
            mkdir -p $PROJECT_DIR
            cd $PROJECT_DIR

            # Удаляем старые файлы
            sudo rm -rf $PROJECT_DIR/*

            # Обновляем клонирование через SSH (нужен Deploy key)
            git clone git@github.com:niftaliyev/2el-front.git .

            # Проверяем что package.json есть
            if [ ! -f package.json ]; then
              echo "📌 package.json не найден — деплой прерван"
              exit 1
            fi

            # Загружаем NVM
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 20
            nvm use 20

            # Установка зависимостей и билд
            npm install --production
            npm run build

            # Перезапуск через PM2
            pm2 describe 2el-front > /dev/null
            if [ $? -eq 0 ]; then
              pm2 reload 2el-front
            else
              pm2 start npm --name "2el-front" -- start
            fi
            pm2 save
