name: Deploy Frontend

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/2el-front:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/2el-front:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/2el-front:latest
            docker stop 2el-front || true
            docker rm 2el-front || true
            docker run -d \
              -p 3000:3000 \
              --name 2el-front \
              ${{ secrets.DOCKER_USERNAME }}/2el-front:latest
